# -*- coding: utf-8 -*-
"""LSTM_Attitude_Estimation_Incremental.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/nsparag/LSTM-INC/blob/main/LSTM_Attitude_Estimation_Incremental.ipynb

## **Import Libraries**
"""

from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dropout, Dense
from tensorflow.keras.layers import Flatten, LSTM, Conv1D, RNN, SimpleRNN
from tensorflow.keras.layers import GlobalMaxPooling1D, Bidirectional
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Embedding
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Concatenate
from tensorflow.keras.layers import Bidirectional
from sklearn import preprocessing
from tensorflow.keras import regularizers
from sklearn.metrics import mean_squared_error
from math import sqrt
import pandas as pd
import numpy as np
import re
from tensorflow.keras.utils import plot_model
from tensorflow.keras import regularizers
import matplotlib.pyplot as plt
import math
from scipy.io import loadmat
import time

"""## **Import Data**"""

df = pd.read_excel('/content/sample_data/D1.xlsx')
df.head()
data1=np.array(df)
print(data1.shape)
data=data1[0:data1.shape[0],:]
print(data.shape)

dataX = data[:,0:9];
dataY = data[:,9:12]

min_max_scaler = preprocessing.MinMaxScaler()
dataX = min_max_scaler.fit_transform(dataX)

"""## **Split Training and Testing Data**"""

split = 10000
dataXt = dataX[:split]
dataYt = dataY[:split]
dataXv = dataX[split:]
dataYv = dataY[split:]

input_dim = dataXt.shape[1]

print("input_dim:", input_dim)
print("\nTraining Testing")
print(dataXt.shape[0],dataXv.shape[0])

timestep = 2
Xphithetapsi = dataXt
Xphithetapsi = array(Xphithetapsi).reshape(split//timestep, timestep, input_dim)
Yphithetapsi = array(dataYt[0::timestep])
print("Xphithetapsi shape",Xphithetapsi.shape)
print("Yphithetapsi shape",Yphithetapsi.shape)

"""## **Model desing and Training**"""

inputs = Input(name='inputs',shape=[timestep,input_dim])
layer = LSTM(50, return_sequences=True)(inputs)
layer = Dropout(0.25)(layer)
layer = LSTM(20)(layer)
outputs = Dense(3, activation='linear')(layer)

modelphithetapsi1 = Model(inputs=[inputs],outputs=[outputs])

# Compile
modelphithetapsi1.compile(optimizer='RMSprop', loss='mean_squared_error',metrics = ['accuracy'])
modelphithetapsi1.summary()

history = modelphithetapsi1.fit(Xphithetapsi, Yphithetapsi,
                       epochs=20,
                       verbose=0,
                       batch_size=50)

print('Model Training done')

"""## **Offline Predictions**"""

results = []
Xtestt = dataXv[:-1]
Ytest = dataYv[:-1]

Ytest = array(Ytest[1::timestep])
Xtest = array(Xtestt[:,0:9])

test_input = np.column_stack((Xtest,Xtestt[:,9:12]))
ip = array(test_input).reshape(test_input.shape[0]//timestep, timestep, input_dim)
test_output = modelphithetapsi1.predict(ip)
test_output = array(test_output)

results = np.array(test_output)
results = results.reshape(test_input.shape[0]//timestep,3)
print(results.shape)

"""## **Incremental Learning Model**"""

# new model for incremental learning
model = Model(inputs=[inputs],outputs=[outputs])
model.compile(optimizer='RMSprop', loss='mean_squared_error',metrics = ['accuracy'])
model.summary()
#copy weights
Wsave = modelphithetapsi1.get_weights()
model.set_weights(Wsave)

wgt = model.get_weights()
print(wgt[1])

result = []
stepinit = 3000
araya = [stepinit, stepinit,stepinit, stepinit, stepinit, stepinit, stepinit, stepinit]
for j in range(0,array(araya).shape[0]):
    XtestA = []
    step = araya[j]
    pt = stepinit*j
    Xtestt = dataXv[pt:pt+step]
    Ytest = dataYv[pt:pt+step]
    Ytest = array(Ytest[0::timestep])
    Xtest = array(Xtestt[:,0:9])

    test_input = np.column_stack((Xtest,Xtestt[:,9:12]))
    XtestA = test_input
    ip = array(XtestA).reshape(step//timestep, timestep, input_dim)
    test_output = model.predict(ip)
    test_output = array(test_output)
    result.append(test_output)
    Xtest1 = ip

    wgt = model.get_weights()
#     print(wgt[1])
    start = time.time()
    history = model.fit(Xtest1, Ytest,
                            epochs=20,
                            verbose=0,
                            batch_size=50)
    end = time.time()
    print(end - start)
result = np.array(result)
result = result.reshape((stepinit*array(araya).shape[0]//timestep,3))
print(result.shape)

result1 = []
XtestA = []
step = (data.shape[0]-split)-stepinit*array(araya).shape[0]
pt = stepinit*array(araya).shape[0]
Xtestt = dataXv[pt:pt+step]
Ytest = dataYv[pt:pt+step]
Ytest = array(Ytest[1::timestep])
Xtest = array(Xtestt[:,0:9])

test_input = np.column_stack((Xtest,Xtestt[:,9:12]))
ip = array(test_input).reshape(step//timestep, timestep, input_dim)
test_output = model.predict(ip)
test_output = array(test_output)
result1.append(test_output)

result1 = np.array(result1)
result1 = result1.reshape(test_input.shape[0]//timestep,3)
print(result1.shape)

print(result.shape)
print(result1.shape)

results = np.vstack((result,result1))
print(results.shape)

"""## **Compute RMSE and Print Results**"""

Yt1 = dataYv
Yt = array(Yt1[0::timestep])
test_output = np.array(results)
test_output = test_output.reshape((Yt.shape[0],3))


from sklearn.metrics import mean_squared_error
from math import sqrt
rmsephi = sqrt(mean_squared_error(Yt[:,0], test_output[:,0]))
print("RMSE phi",rmsephi)

rmsetheta = sqrt(mean_squared_error(Yt[:,1], test_output[:,1]))
print("RMSE theta",rmsetheta)

rmsepsi = sqrt(mean_squared_error(Yt[:,2], test_output[:,2]))
print("RMSE phi",rmsepsi)

print(rmsephi,rmsetheta,rmsepsi)

plt.plot(Yt[:,0])
plt.plot(test_output[:,0])
plt.title('Phi/Roll')
plt.xlabel('samples')
plt.ylabel('Roll angle')
plt.legend(['Reference', 'Predicted'], loc = 'upper right')
plt.show()

plt.plot(Yt[:,1])
plt.plot(test_output[:,1])
plt.title('Theta/Pitch')
plt.xlabel('samples')
plt.ylabel('Pitch angle')
plt.legend(['Reference', 'Predicted'], loc = 'upper right')
plt.show()

plt.plot(Yt[:,2])
plt.plot(test_output[:,2])
plt.title('Psi/Yaw')
plt.xlabel('samples')
plt.ylabel('Yaw angle')
plt.legend(['Reference', 'Predicted'], loc = 'upper right')
plt.show()